language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t vladimirpodr/docker-react -f Dockerfile.dev .
script:
    -docker run -e CI=true vladimirpodr/docker-react npm run test